// license Jonas Immanuel Frey GPL
//
// Batch tool: for every image in texture_roller/, clone a template project
// (default `roller7`) with that image as its source, save the cloned project
// under projects/, and export the STL the app would produce.
//
// STLs are generated by driving the real app in a headless browser, so the
// geometry pipeline is byte-for-byte the same as a manual "Download STL".
//
// Usage:
//   node tools/batch_export.mjs              # all images, roller7 template
//   LIMIT=1 node tools/batch_export.mjs      # first N images (smoke test)
//   TEMPLATE=roller5 node tools/batch_export.mjs   # use a different template
//
// Requires the Vite dev server to be running (npm run dev) so the project
// store API and module graph are served.

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const IMAGES_DIR   = path.join(ROOT, 'texture_roller');
const PROJECTS_DIR = path.join(ROOT, 'projects');
const STL_DIR      = path.join(ROOT, 'texture_roller_stls');
const TEMPLATE_NAME = process.env.TEMPLATE || 'roller7';
const TEMPLATE     = path.join(PROJECTS_DIR, `${TEMPLATE_NAME}.json`);

const BASE_URL = process.env.BASE_URL || 'http://localhost:5173/';
const LIMIT = process.env.LIMIT ? parseInt(process.env.LIMIT, 10) : Infinity;

// Drive headless Chrome via playwright-core (no bundled browser download);
// point it at the system Chrome, overridable with CHROME=/path env.
const CHROME = process.env.CHROME || '/usr/bin/google-chrome';

const { chromium } = await import('playwright-core');

function mimeForExt(ext) {
  switch (ext.toLowerCase()) {
    case '.png':  return 'image/png';
    case '.jpg':
    case '.jpeg': return 'image/jpeg';
    case '.webp': return 'image/webp';
    case '.bmp':  return 'image/bmp';
    default:      return 'application/octet-stream';
  }
}

async function buildProjectFor(imgFile, template) {
  const ext = path.extname(imgFile);
  const base = path.basename(imgFile, ext);
  const bytes = await fs.readFile(path.join(IMAGES_DIR, imgFile));
  const dataUrl = `data:${mimeForExt(ext)};base64,${bytes.toString('base64')}`;

  const data = structuredClone(template);
  data.savedAt = new Date().toISOString();
  data.source = {
    filename: base,            // matches the template's extension-less convention
    inputType: 'image',
    imageDataUrl: dataUrl
  };
  delete data.source.stl;      // ellipse project has no source STL
  return { base, data };
}

async function main() {
  await fs.mkdir(STL_DIR, { recursive: true });
  const template = JSON.parse(await fs.readFile(TEMPLATE, 'utf8'));

  let images = (await fs.readdir(IMAGES_DIR))
    .filter((f) => /\.(png|jpe?g|webp|bmp)$/i.test(f))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  if (Number.isFinite(LIMIT)) images = images.slice(0, LIMIT);

  console.log(`${images.length} image(s) to process.`);

  const browser = await chromium.launch({ headless: true, executablePath: CHROME });
  const page = await browser.newPage();
  // The large-STL warning is a window.confirm — always accept it.
  page.on('dialog', (d) => d.accept().catch(() => {}));
  page.on('pageerror', (e) => console.error('  [page error]', e.message));

  await page.goto(BASE_URL, { waitUntil: 'load' });
  await page.waitForSelector('#projectFileInput', { state: 'attached' });

  let ok = 0, fail = 0;
  for (const img of images) {
    const { base, data } = await buildProjectFor(img, template);
    const projPath = path.join(PROJECTS_DIR, `${base}.json`);
    await fs.writeFile(projPath, JSON.stringify(data));

    try {
      // Upload the freshly-written project; the change handler runs
      // applyProjectData → processing. Large meshes (the troller is ~1.1M
      // triangles) are gated behind a "Regenerate mesh" button instead of
      // auto-building, so processing settles into one of two states.
      await page.setInputFiles('#projectFileInput', projPath);

      // Wait until processing settles: either export is enabled (small mesh
      // auto-built) or the Regenerate button is shown (deferred large mesh).
      await page.waitForFunction(
        () => {
          const dl = document.getElementById('downloadSTL');
          const rw = document.getElementById('regenButtonWrap');
          return (dl && !dl.disabled) || (rw && !rw.classList.contains('hidden'));
        },
        { timeout: 120000 }
      );

      // If the mesh was deferred, click Regenerate to force the build.
      const deferred = await page.evaluate(() => {
        const rw = document.getElementById('regenButtonWrap');
        return rw && !rw.classList.contains('hidden');
      });
      if (deferred) {
        await page.click('#regenBtn');
        await page.waitForFunction(
          () => {
            const b = document.getElementById('downloadSTL');
            return b && !b.disabled;
          },
          { timeout: 120000 }
        );
      }

      const [download] = await Promise.all([
        page.waitForEvent('download', { timeout: 120000 }),
        page.click('#downloadSTL')
      ]);
      const outName = download.suggestedFilename() || `${base}.stl`;
      const outPath = path.join(STL_DIR, outName);
      await download.saveAs(outPath);
      const st = await fs.stat(outPath);
      ok++;
      console.log(`  ✓ ${img} → ${outName} (${(st.size / 1024 / 1024).toFixed(1)} MB)`);
    } catch (err) {
      fail++;
      console.error(`  ✗ ${img}: ${err.message}`);
    }
  }

  await browser.close();
  console.log(`\nDone. ${ok} ok, ${fail} failed.`);
  if (fail) process.exitCode = 1;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
