// license Jonas Immanuel Frey GPL
//
// Batch tool: for every image in the texture-roller images dir, clone a preset
// project with that image as its source and export the STL the app would
// produce.
//
// STLs are generated by driving the real app in a headless browser, so the
// geometry pipeline is byte-for-byte the same as a manual "Download STL".
//
// Env vars (all optional):
//   PRESET / TEMPLATE  preset project basename in projects/ (default roller7)
//   AUTO_STRETCH       "1" → click "Auto-stretch levels" per image before build
//   LIMIT              only the first N images (smoke test)
//   IMAGES_DIR         source images dir (default: first existing of
//                      texture_roller / texture_rollers)
//   PROJ_OUT_DIR       where per-image upload projects are written
//                      (default projects/; set to a temp dir to avoid clobber)
//   STL_DIR            output dir for STLs (default texture_roller_stls/)
//   CHROME             Chrome/Chromium binary (default: first existing known one)
//   BASE_URL           dev server URL (default http://localhost:5173/)
//
// Usage:
//   node tools/batch_export.mjs
//   PRESET=troller_cobble AUTO_STRETCH=1 IMAGES_DIR=texture_rollers \
//     PROJ_OUT_DIR=/tmp/cobble_proj node tools/batch_export.mjs
//
// Requires the Vite dev server to be running (npm run dev).

import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

function firstExisting(paths) {
  return paths.find((p) => p && existsSync(p));
}

const PROJECTS_DIR = path.join(ROOT, 'projects');
const PRESET   = process.env.PRESET || process.env.TEMPLATE || 'roller7';
const TEMPLATE = path.join(PROJECTS_DIR, `${PRESET}.json`);

// Images dir: explicit env, else whichever of the two conventional names exists.
const IMAGES_DIR = process.env.IMAGES_DIR
  ? path.resolve(process.env.IMAGES_DIR)
  : firstExisting([path.join(ROOT, 'texture_roller'), path.join(ROOT, 'texture_rollers')])
    || path.join(ROOT, 'texture_roller');

const STL_DIR = process.env.STL_DIR
  ? path.resolve(process.env.STL_DIR)
  : path.join(ROOT, 'texture_roller_stls');
const PROJ_OUT_DIR = process.env.PROJ_OUT_DIR
  ? path.resolve(process.env.PROJ_OUT_DIR)
  : PROJECTS_DIR;
const AUTO_STRETCH = process.env.AUTO_STRETCH === '1';

const BASE_URL = process.env.BASE_URL || 'http://localhost:5173/';
const LIMIT = process.env.LIMIT ? parseInt(process.env.LIMIT, 10) : Infinity;

// Chrome binary: env override, else the first known-good one on this machine.
const CHROME = process.env.CHROME || firstExisting([
  '/home/legion5pro/.cache/puppeteer/chrome/linux-149.0.7827.22/chrome-linux64/chrome',
  '/usr/bin/google-chrome',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/chromium-browser',
  '/snap/bin/chromium'
]);

// Playwright: prefer installed playwright-core; fall back to a sibling
// project's bundled playwright when playwright-core isn't installed here.
let chromium;
try {
  ({ chromium } = await import('playwright-core'));
} catch {
  ({ chromium } = await import('/home/legion5pro/code/monaco-editor/node_modules/playwright/index.mjs'));
}

function mimeForExt(ext) {
  switch (ext.toLowerCase()) {
    case '.png':  return 'image/png';
    case '.jpg':
    case '.jpeg': return 'image/jpeg';
    case '.webp': return 'image/webp';
    case '.bmp':  return 'image/bmp';
    default:      return 'application/octet-stream';
  }
}

async function buildProjectFor(imgFile, template) {
  const ext = path.extname(imgFile);
  const base = path.basename(imgFile, ext);
  const bytes = await fs.readFile(path.join(IMAGES_DIR, imgFile));
  const dataUrl = `data:${mimeForExt(ext)};base64,${bytes.toString('base64')}`;

  const data = structuredClone(template);
  data.savedAt = new Date().toISOString();
  data.source = {
    filename: base,            // matches the template's extension-less convention
    inputType: 'image',
    imageDataUrl: dataUrl
  };
  delete data.source.stl;      // ellipse preset has no source STL
  return { base, data };
}

// Wait until processing settles: either export is enabled (small mesh
// auto-built) or the Regenerate button is shown (deferred large mesh).
async function waitSettled(page) {
  await page.waitForFunction(
    () => {
      const dl = document.getElementById('downloadSTL');
      const rw = document.getElementById('regenButtonWrap');
      return (dl && !dl.disabled) || (rw && !rw.classList.contains('hidden'));
    },
    { timeout: 120000 }
  );
}

// If the mesh build was deferred behind the Regenerate gate, force it and wait
// for the export button to enable.
async function forceBuildIfDeferred(page) {
  const deferred = await page.evaluate(() => {
    const rw = document.getElementById('regenButtonWrap');
    return rw && !rw.classList.contains('hidden');
  });
  if (deferred) {
    await page.click('#regenBtn');
    await page.waitForFunction(
      () => {
        const b = document.getElementById('downloadSTL');
        return b && !b.disabled;
      },
      { timeout: 120000 }
    );
  }
}

async function main() {
  if (!existsSync(TEMPLATE)) {
    console.error(`Preset not found: ${TEMPLATE}`);
    process.exit(1);
  }
  if (!existsSync(IMAGES_DIR)) {
    console.error(`Images dir not found: ${IMAGES_DIR}`);
    process.exit(1);
  }
  await fs.mkdir(STL_DIR, { recursive: true });
  await fs.mkdir(PROJ_OUT_DIR, { recursive: true });
  const template = JSON.parse(await fs.readFile(TEMPLATE, 'utf8'));

  let images = (await fs.readdir(IMAGES_DIR))
    .filter((f) => /\.(png|jpe?g|webp|bmp)$/i.test(f))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  if (Number.isFinite(LIMIT)) images = images.slice(0, LIMIT);

  console.log(`Preset: ${PRESET} | auto-stretch: ${AUTO_STRETCH} | ${images.length} image(s)`);
  console.log(`Images: ${IMAGES_DIR}`);
  console.log(`STL out: ${STL_DIR}`);

  const browser = await chromium.launch({ headless: true, executablePath: CHROME });
  const page = await browser.newPage();
  // The large-STL warning is a window.confirm — always accept it.
  page.on('dialog', (d) => d.accept().catch(() => {}));
  page.on('pageerror', (e) => console.error('  [page error]', e.message));

  await page.goto(BASE_URL, { waitUntil: 'load' });
  await page.waitForSelector('#projectFileInput', { state: 'attached' });

  let ok = 0, fail = 0;
  for (const img of images) {
    const { base, data } = await buildProjectFor(img, template);
    const projPath = path.join(PROJ_OUT_DIR, `${base}.json`);
    await fs.writeFile(projPath, JSON.stringify(data));

    try {
      // Upload the project; the change handler runs applyProjectData →
      // processing → either auto-builds or shows the Regenerate gate.
      await page.setInputFiles('#projectFileInput', projPath);
      await waitSettled(page);

      // Auto-stretch levels: sets black/white points to the processed image's
      // actual min/max range, then reprocesses. Done before the mesh build so
      // we only build once. state.processed is populated by the preview phase,
      // which has already run by the time waitSettled returns.
      if (AUTO_STRETCH) {
        await page.click('#autoStretch');
        await waitSettled(page);
      }

      await forceBuildIfDeferred(page);

      const [download] = await Promise.all([
        page.waitForEvent('download', { timeout: 120000 }),
        page.click('#downloadSTL')
      ]);
      const outName = download.suggestedFilename() || `${base}.stl`;
      const outPath = path.join(STL_DIR, outName);
      await download.saveAs(outPath);
      const st = await fs.stat(outPath);
      ok++;
      console.log(`  ✓ ${img} → ${outName} (${(st.size / 1024 / 1024).toFixed(1)} MB)`);
    } catch (err) {
      fail++;
      console.error(`  ✗ ${img}: ${err.message}`);
    }
  }

  await browser.close();
  console.log(`\nDone. ${ok} ok, ${fail} failed.`);
  if (fail) process.exitCode = 1;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
